# -*- coding: utf-8 -*-
"""project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vg3ZDVGTR-K3w0vEJkWk_19Vfc-HaUTn
"""

import pandas as pd
data = pd.read_excel("/content/Data.xlsx")
print(data.head(5))
print(data.info())

data["Date"] = pd.to_datetime(data["Date"])
data["Sales"] = pd.to_numeric(data["Sales"])
data["Category"] = data["Category"].astype(str)

data.set_index("Date", inplace=True)

import matplotlib.pyplot as plt
monthly_sales = data["Sales"].resample("ME").sum()
quarterly_sales = data["Sales"].resample("QE").sum()

plt.figure()
monthly_sales.plot()
plt.title("Monthly Sales Trend")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("monthly_sales.png")
plt.close()

plt.figure()
quarterly_sales.plot()
plt.title("Quarterly Sales Trend")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("quarterly_sales.png")
plt.close()

category_sales = data.groupby("Category")["Sales"].sum()

plt.figure()
category_sales.plot(kind="bar")
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.savefig("category_sales_bar.png")
plt.close()

plt.figure()
category_sales.plot(kind="pie", autopct="%1.1f%%")
plt.title("Category-wise Sales Share")
plt.ylabel("")
plt.tight_layout()
plt.savefig("category_sales_pie.png")
plt.close()

summary = {
    "Total Sales": data["Sales"].sum(),
    "Best Category": category_sales.idxmax(),
    "Best Month": monthly_sales.idxmax().strftime("%Y-%m")
}

print("Summary Report")
print("----------------")
for k, v in summary.items():
    print(f"{k}: {v}")